apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stable-diffusion-gpu
  labels:
    cloud.googleapis.com/location: REGION
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/network-interfaces: '[{"network":"NETWORK","subnetwork":"SUBNET"}]'
        run.googleapis.com/vpc-access-egress: 'all-traffic'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: '{"demo-ui":["sd-torchserve"]}'
        run.googleapis.com/gpu-zonal-redundancy-disabled: 'true'
    spec:
      containerConcurrency: 10
      timeoutSeconds: 600
      containers:
      - name: demo-ui
        image: REGION-docker.pkg.dev/PROJECT_ID/demo/demo-ui:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SD_API_ENDPOINT
          value: http://localhost:8181
        - name: STORAGE_BUCKET_NAME
          value: PROJECT_ID-images
        # - name: GENERATOR_URL
        #   value: http://localhost:8183 # or change this to sidecar for generator
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
      - name: sd-torchserve
        image: REGION-docker.pkg.dev/PROJECT_ID/demo/torchserve-sdxl-turbo
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: TS_INFERENCE_ADDRESS
            value: "http://0.0.0.0:8181"
          - name: STORAGE_BUCKET_NAME
            value: PROJECT_ID-images
          - name: MODEL_BUCKET_NAME
            value: PROJECT_ID-models
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: latest
        resources:
          limits:
            cpu: '6'
            nvidia.com/gpu: '1'
            memory: 16Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8181
      nodeSelector:
        run.googleapis.com/accelerator: nvidia-l4